# Generated by Django 6.0.2 on 2026-02-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patientdetails_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctordetails',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doctordetails',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='doctordetails',
            name='specialization',
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='Address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='ContactNumber',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='Doctor_ID',
            field=models.CharField(default='D001', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='Full_Name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='Sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='Specialization',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
