# Generated by Django 6.0.2 on 2026-02-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_doctordetails_email_remove_doctordetails_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='status',
        ),
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='time',
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='Appointment_Date',
            field=models.DateField(default='2026-01-01'),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='Appointment_ID',
            field=models.CharField(default='A001', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='Appointment_Time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='Bldg_No',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='Doctor_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='Patient_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='Room_No',
            field=models.CharField(default='', max_length=10),
        ),
    ]
