# Generated by Django 6.0.2 on 2026-02-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_appointmentdetails_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetails',
            name='Appointment_ID',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='Doctor_ID',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='Patient_ID',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
